name: 'Make Repo Public'
description: 'Changes the repository visibility to public at a specified date and time'
author: Shay Zluf
inputs:
  target_date:
    description: 'The date and time when the repository should be made public'
    required: true
  gh_pat:
    description: 'The GitHub Personal Access Token'
    required: true
  webhook_url:
    description: 'The URL of the webhook to call'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        CURRENT_DATE=$(date +%s)
        if [ $CURRENT_DATE -ge (${{ inputs.target_date }}-600) ]; then
          RESPONSE=$(curl \
            -s \
            -o /dev/null \
            -w "%{http_code}" \
            -X PATCH \
            -H "Authorization: token ${{ inputs.gh_pat }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"visibility":"public"}')

          if [ $RESPONSE -eq 200 ]; then
            echo "Repository visibility successfully changed to public."
            echo 'VISIBILITY_CHANGED=true' >> $GITHUB_ENV
          else
            echo "Failed to change repository visibility. HTTP response code: $RESPONSE"
            exit 1
          fi
        else
          echo "Current date is not yet the target date. Skipping."
        fi
      shell: bash
    - run: |
        if [ $VISIBILITY_CHANGED == 'true' ]; then
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
            -H "Authorization: token ${{ inputs.gh_pat }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/make_repo_public.yml/disable)
          if [ $RESPONSE -ne 204 ]; then
            echo "Failed to disable workflow. HTTP response code: $RESPONSE"
            exit 1
          fi
        fi
      shell: bash
    - run: |
        if [ "${{ inputs.webhook_url }}" != "" ]; then
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" \
            -d '{
              "repository": "${{ github.repository }}",
              "target_date": "${{ inputs.target_date }}",
              "visibility_changed": "${{ env.VISIBILITY_CHANGED }}",
              "verification": "${{ inputs.verification }}"
            }' \
            ${{ inputs.webhook_url }})
          if [ $RESPONSE -ne 200 ]; then
            echo "Failed to call webhook. HTTP response code: $RESPONSE"
            exit 1
          fi
        fi
      shell: bash
